export const UserType = {
    architect : "Architect",
    dealer : "Dealer",
    retailer : "Retailer",
    carpenter : "Carpenter",
}

export const StateName = {
    ANDHRA_PRADESH: 'Andhra Pradesh',
    ARUNACHAL_PRADESH: 'Arunachal Pradesh',
    ASSAM: 'Assam',
    BIHAR: 'Bihar',
    CHHATTISGARH: 'Chhattisgarh',
    GOA: 'Goa',
    GUJARAT: 'Gujarat',
    HARYANA: 'Haryana',
    HIMACHAL_PRADESH: 'Himachal Pradesh',
    JHARKHAND: 'Jharkhand',
    KARNATAKA: 'Karnataka',
    KERALA: 'Kerala',
    MADHYA_PRADESH: 'Madhya Pradesh',
    MAHARASHTRA: 'Maharashtra',
    MANIPUR: 'Manipur',
    MEGHALAYA: 'Meghalaya',
    MIZORAM: 'Mizoram',
    NAGALAND: 'Nagaland',
    ODISHA: 'Odisha',
    PUNJAB: 'Punjab',
    RAJASTHAN: 'Rajasthan',
    SONGKHLA: 'Songkhla',
    TAMIL_NADU: 'Tamil Nadu',
    TELANGANA: 'Telangana',
    TRIPURA: 'Tripura',
    UTTAR_PRADESH: 'Uttar Pradesh',
    UTTARAKHAND: 'Uttarakhand',
    WEST_BENGAL: 'West Bengal',
    ANDAMAN_AND_NICOBAR_ISLANDS: 'Andaman and Nicobar Islands',
    CHANDIGARH: 'Chandigarh',
    DADRA_AND_NAGAR_HAVALI_AND_DAMAN_AND_DIU: 'Dadra and Nagar Haveli and Daman and Diu',
    DELHI: 'Delhi',
    JAMMU_AND_KASHMIR: 'Jammu and Kashmir',
    LAKSHADWEEP: 'Lakshadweep',
    LADAKH: 'Ladakh',
    PUDUCHERRY: 'Puducherry'
};
